### ISSUE TITLE
Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353

### ISSUE THREAD

**Issue by LiveRock** [osociety/network_tools_flutter#28]
Hi

I am getting these in Flutter ios app.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: Too many open files, errno = 24), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1051:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2558:15)
<asynchronous suspension>
#2      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#3      MdnsScanner.findingMdnsWithAddress (package:network_tools/src/mdns_scanner/mdns_scanner.dart:73:5)
```

How do I resolve it?

**Comment by git-elliot** [comment]
Can you tell us how did you get this error? what values for range you used for subnet

**Comment by LiveRock** [comment]
1. I am trying to do a Host Scan
2. 1 -254

**Comment by git-elliot** [comment]
Please attach a reproducible example so that we can test on our machine

**Comment by LiveRock** [comment]
It is working now after a Flutter upgrade
